---
title: "BAE 565 Github Week Outline"
date: "01-15-2021"
output:
  word_document: default
  pdf_document: default
  html_document: default
auther: Brock Kamrath
---

I have worked through the happy git website and have read both the of the articles you suggested. From this work I have prepared a general outline for the github/version control week. Please note that this is just a general idea of what I am thinking. I have not yet prepared any material towards this goal or developed an excerise that would serve as homework, though I would want it to deal with forking and cloning a repo to Github then to a local computer, setting the upstream repo on a local computer to pull from, making a change on a local computer, pushing your change back to Github, and then submitting a pull request back to the upstream repo.

# Work to be done prior to 2/2/21
* Read sections 1-4 of Excuse Me, Do You Have a Moment to Talk About Version Control?
* Read Our path to better science in less time using open data science tools
* Complete Section "1. Installation" on https://happygitwithr.com/

# 2/2/21: In class work
* 0 - 20 min: Article discussion, github questions, and installation troubleshooting
* 20 - 30 min: Discussion of Terminal and Git (nuts and bolts)
* 30 - 50 min: Work through Chapter 12: Connect RStudio to Git an GitHub
  + Do this together using slides to allow for quick troubleshooting
* 50 - 60 min: Discussion of Github terminology
* 60 - 70 min: Start Chapter 15: New project, GitHub first
* 70 - 75 min: Quick discussion of work to do prior to next class

# Work to be done prior to 2/4/21
* Read sections 8-13 of Excuse Me, Do You Have a Moment to Talk About Version Control?
* Finish Chapter 15

# 2/4/21: In Class work
* 0 - 15 min: Article discussion with questions focusing on terminology
* 15 - 35 min: Work through Chapter 18: Test drive R Markdown 
* 35 - 50 min: Workflow lecture markdown files instead of .docx file and general questions
* 50 - 75 min: Present and discuss excerise to be due the following Tuesday 2/9/21
